### ISSUE TITLE
Move to MaybeUninit

### ISSUE THREAD

**Issue by lu-zero** [rust-av/vpx-rs#15]
Current rust uses [maybeuninit](https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html) instead of uninitialized.

[this](https://github.com/rust-av/aom-rs/commit/f3296061a95d94204cad6f8f3f662198807b9892) address the same issue for aom.

**Comment by Luni-4** [comment]
This one should be fixed in #17 and #18
